JBOwnable
jbx-protocol/juice-721-delegate pull request #128
Opened 2023-03-08 22:09 UTC by xBA5ED

2023-04-02 22:37 UTC, mejango requested changes

2023-04-02 22:37 UTC, mejango commented on contracts/JBTiered721Delegate.sol
> -contract JBTiered721Delegate is JB721Delegate, Ownable, IJBTiered721Delegate, IERC2981 {
why move Ownable to the superclass? Can we keep this as JBOwnable here @xBA5ED ?

2023-04-18 20:54 UTC, mejango commented on contracts/JBTiered721Delegate.sol
> -contract JBTiered721Delegate is JB721Delegate, Ownable, IJBTiered721Delegate, IERC2981 {
@xBA5ED

2023-04-18 20:55 UTC, mejango commented
lets undraft this PR!

2023-05-03 06:21 UTC, mejango commented
@xBA5ED can we also add a `requiresPermission` modifier to `adjustTiers` so that a project owner can give an Operator permission to do so on their behalf?

2023-05-05 03:13 UTC, mejango approved these changes

2023-05-05 06:15 UTC, viraj124 approved these changes

2023-05-05 19:34 UTC, merged